import { Inter } from "next/font/google";
import "../globals.css";
import VideoLeftSidebar from "./VideoCompnents/VideoLeftSidebar";
import AuthProvider from "../Provider/AuthProvider";
import FeedHeader from "../(feed)/FeedComponents/FeedHeader";
import RightSidebar from "../(feed)/FeedComponents/Sidebar/RightSidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default function VideoLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <main>
          <AuthProvider>
            <FeedHeader />
            <div className="mt-16 flex justify-between">
              <div className="fixed left-0">
                <VideoLeftSidebar />
              </div>
              <div className="mx-2 lg:mx-[270px]">{children}</div>
              <div className="fixed right-0">
                <RightSidebar />
              </div>
            </div>
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
